### PR TITLE
Initial Code

### PR DESCRIPTION
**Pull request by manuelrorizoliveira**

### CODE REVIEW

**Comment by manueloliveira19** [comment]
@CodiumAI-Agent /review

**Comment by manueloliveira19** [comment]
@CodiumAI-Agent /describe

**Comment by manueloliveira19** [comment]
@CodiumAI-Agent /improve

**Comment by manueloliveira19** [comment]
@CodiumAI-Agent /describe

**Comment by manuelrorizoliveira** [comment]
@CodiumAI-Agent /ask is there any unused using in the file?

**Comment by manuelrorizoliveira** [comment]
@CodiumAI-Agent /review

**Comment by manuelrorizoliveira** [comment]
@CodiumAI-Agent /ask is there any unused using in the file?

**Comment by manuelrorizoliveira** [comment]
@CodiumAI-Agent /improve

**Pull request closed without merging**
